<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<WebElementEntity>
   <description/>
   <name>i_Choose a category_v-icon notranslate mdi _e7fef0</name>
   <tag/>
   <elementGuidId>7db4316f-221c-4794-b43b-c1d1dddcf450</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div/div/div/div/div/div[2]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-menu-down theme--dark primary--text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@id="app"]/div[@class="v-menu__content theme--dark menuable__content__active v-small-dialog__menu-content"]/div[@class="v-small-dialog__content"]/div[@class="v-input v-input--is-label-active v-input--is-dirty v-input--is-focused theme--dark v-text-field v-text-field--filled v-text-field--is-booted v-text-field--enclosed v-select v-select--is-menu-active primary--text"]/div[@class="v-input__control"]/div[@class="v-input__slot"]/div[@class="v-select__slot"]/div[@class="v-input__append-inner"]/div[@class="v-input__icon v-input__icon--append"]/i[@class="v-icon notranslate mdi mdi-menu-down theme--dark primary--text"]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div[2]/div/div/div/div/div/div[2]/div/i</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div[2]/div/i</value>
   </webElementXpaths>
</WebElementEntity>
